#!/bin/sh
#set -x #debug

# Este comando se utilizó para limpiar los lugares de la información del narco y
# generar un diccionario de lugares.

FILES=()
DICT=palabras-eliminadas.dict

usage() {
	echo $(basename $0) "[-h] [-f diccionario] termino-a-borrar archivo_1 [ ... archivo_n ]"
	exit 1
}

for opt do
	case $opt in
	-f)
		shift
		DICT=$1;
	;;
	-h)
		usage
	;;
	*)
		[ -z "$TERMINO" ] && {
			TERMINO="$1"
		} || {
			[ -n "$1" ] && FILES[${#FILES[@]}]=\'"$1"\'
		}
	;;
	esac
	shift
done

[ -z "$TERMINO" -o -z "$FILES" -o -z "$DICT" ] && usage

echo "$TERMINO" >> "$DICT"
eval sed -i -e \''s/^[ \t]\+"'"$TERMINO"'",\?[ \t]*$//g'\' ${FILES[@]}
